version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc
    - nolintlint
    - revive
  settings:
    errcheck:
      check-type-assertions: true
    revive:
      rules:
        - name: unexported-return
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - prealloc
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
